### ISSUE TITLE
digitUppercase10000.21转换错误

### ISSUE THREAD

**Issue by sakura-monster** [HandsomeWolf/pixiu-number-toolkit#11]
<img width="143" alt="Snipaste_2024-07-23_11-33-18" src="https://github.com/user-attachments/assets/f06c9fa5-afb6-48b4-a02f-0037090a907b">

**Comment by HandsomeWolf** [comment]
抱歉，在3.0.3版本中已修复问题，并且函数名改了。请参考最新开发文档：https://www.muchappy.com/open_source/pixiu-number-toolkit/basic/digit-chinese-uppercase
