### ISSUE TITLE
数字转中文是否缺少零

### ISSUE THREAD

**Issue by f5l5y5** [HandsomeWolf/pixiu-number-toolkit#5]
例如：120012 输出：一十二万一十二 
正常：一十二万零一十二

**Comment by HandsomeWolf** [comment]
![image](https://github.com/HandsomeWolf/pixiu-number-toolkit/assets/27292774/a1e2db5b-e86e-4733-8230-679c5c545c1c)
确实，在提取“万”后，0012被识别成了12，导致0丢失，已修复，单元测试已跑过。
